{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "def scrap_fifa(year):\n",
    "    \n",
    "    import pandas as pd\n",
    "    import requests\n",
    "    from itertools import chain\n",
    "    import requests\n",
    "    from bs4 import BeautifulSoup\n",
    "    import numpy as np\n",
    "\n",
    "    l= []\n",
    "    l2= []\n",
    "\n",
    "    # NUMBER OF UPDATES EVERY YEAR:\n",
    "    \n",
    "    if year == 13:\n",
    "        times = 34\n",
    "    \n",
    "    if year == 14:\n",
    "        times = 52\n",
    "    \n",
    "    if year == 15:\n",
    "        times = 59\n",
    "    \n",
    "    if year == 16:\n",
    "        times = 58\n",
    "    \n",
    "    if year == 17:\n",
    "        times = 99\n",
    "    \n",
    "    if year == 18:\n",
    "        times = 84\n",
    "    \n",
    "    if year == 19:\n",
    "        times = 75\n",
    "    \n",
    "    if year == 20:\n",
    "        times = 61\n",
    "    \n",
    "    \n",
    "    for i in range(1,times+1):\n",
    "        \n",
    "        #TAKE THE DATE & FIFA VERSION\n",
    "        \n",
    "        year = str(year)    \n",
    "        request = requests.get('https://sofifa.com/teams?type=club&lg%5B0%5D=16&lg%5B1%5D=19&lg%5B2%5D=31&lg%5B3%5D=53&lg%5B4%5D=13&r=' + year + '00' + '%02d' % i + '&set=true&showCol%5B0%5D=ti&showCol%5B1%5D=oa&showCol%5B2%5D=at&showCol%5B3%5D=md&showCol%5B4%5D=df&showCol%5B5%5D=tb&showCol%5B6%5D=bs&showCol%5B7%5D=bd&showCol%5B8%5D=bp&showCol%5B9%5D=bps&showCol%5B10%5D=cc&showCol%5B11%5D=cp&showCol%5B12%5D=cs&showCol%5B13%5D=cps&showCol%5B14%5D=da&showCol%5B15%5D=dm&showCol%5B16%5D=dw&showCol%5B17%5D=dd&showCol%5B18%5D=dp&showCol%5B19%5D=ip&showCol%5B20%5D=ps&showCol%5B21%5D=sa&showCol%5B22%5D=ta')\n",
    "        content_web = request.content\n",
    "        soup = BeautifulSoup(content_web, 'lxml')\n",
    "        line_date = soup.find_all('title')\n",
    "        date = str(line_date)\n",
    "\n",
    "        # TAKE THE LINK\n",
    "        \n",
    "        name_r1 = 'https://sofifa.com/teams?type=club&lg%5B0%5D=16&lg%5B1%5D=19&lg%5B2%5D=31&lg%5B3%5D=53&lg%5B4%5D=13&r=' + year + '00' + '%02d' % i + '&set=true&showCol%5B0%5D=ti&showCol%5B1%5D=oa&showCol%5B2%5D=at&showCol%5B3%5D=md&showCol%5B4%5D=df&showCol%5B5%5D=tb&showCol%5B6%5D=bs&showCol%5B7%5D=bd&showCol%5B8%5D=bp&showCol%5B9%5D=bps&showCol%5B10%5D=cc&showCol%5B11%5D=cp&showCol%5B12%5D=cs&showCol%5B13%5D=cps&showCol%5B14%5D=da&showCol%5B15%5D=dm&showCol%5B16%5D=dw&showCol%5B17%5D=dd&showCol%5B18%5D=dp&showCol%5B19%5D=ip&showCol%5B20%5D=ps&showCol%5B21%5D=sa&showCol%5B22%5D=ta'\n",
    "        name_r2 = 'https://sofifa.com/teams?type=club&lg%5B0%5D=16&lg%5B1%5D=19&lg%5B2%5D=31&lg%5B3%5D=53&lg%5B4%5D=13&r=' + year + '00' + '%02d' % i + '&set=true&showCol%5B0%5D=ti&showCol%5B1%5D=oa&showCol%5B2%5D=at&showCol%5B3%5D=md&showCol%5B4%5D=df&showCol%5B5%5D=tb&showCol%5B6%5D=bs&showCol%5B7%5D=bd&showCol%5B8%5D=bp&showCol%5B9%5D=bps&showCol%5B10%5D=cc&showCol%5B11%5D=cp&showCol%5B12%5D=cs&showCol%5B13%5D=cps&showCol%5B14%5D=da&showCol%5B15%5D=dm&showCol%5B16%5D=dw&showCol%5B17%5D=dd&showCol%5B18%5D=dp&showCol%5B19%5D=ip&showCol%5B20%5D=ps&showCol%5B21%5D=sa&showCol%5B22%5D=ta&offset=60'\n",
    "    \n",
    "        r1 = requests.get(name_r1)\n",
    "        r2 = requests.get(name_r2)\n",
    "        \n",
    "        \n",
    "        l2.append(date)\n",
    "        l.append(pd.read_html(r1.content))\n",
    "        l.append(pd.read_html(r2.content))\n",
    "        print('appended ',date)    \n",
    "        \n",
    "    # CONCATENATE THE DIFERENT UPDATES AND EXTEND DATE LIST SO THAT THE DIMENSIONS FIT TOGETHER\n",
    "    \n",
    "    df= pd.concat(chain.from_iterable(l))\n",
    "    l3 = np.repeat(l2,len(df)/(times))\n",
    "    \n",
    "    # ADD THE LIST WITH THE DATES & FIFA VERSION TO THE DATABASE\n",
    "    \n",
    "    df['Date']=l3\n",
    "\n",
    "    # SOME FEATURE WORK: \n",
    "    \n",
    "    cols = list(df.columns)\n",
    "    cols = [cols[-1]] + cols[:-1]\n",
    "    df = df[cols]\n",
    "    df = df.drop(['Unnamed: 0'], axis=1)\n",
    "        \n",
    "    \n",
    "    return(df)\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "appended  [<title>Teams FIFA 16 Aug 28, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Sep 21, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Sep 25, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Oct 2, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Oct 9, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Oct 16, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Oct 19, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Oct 23, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Oct 30, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Nov 6, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Nov 12, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Nov 19, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Nov 26, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Dec 3, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Dec 10, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Dec 17, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Dec 24, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Dec 30, 2015 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jan 7, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jan 14, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jan 21, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jan 28, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Feb 4, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Feb 11, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Feb 13, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Feb 18, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Feb 19, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Feb 25, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Mar 3, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Mar 10, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Mar 17, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Mar 24, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Mar 31, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Apr 7, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Apr 14, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Apr 21, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Apr 28, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 May 5, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 May 12, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 May 19, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 May 26, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jun 2, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jun 9, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jun 16, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jun 23, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jun 30, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jul 7, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jul 14, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jul 21, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Jul 28, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Aug 4, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Aug 11, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Aug 18, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Aug 26, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Sep 1, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Sep 8, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Sep 14, 2016 SoFIFA</title>]\n",
      "appended  [<title>Teams FIFA 16 Sep 22, 2016 SoFIFA</title>]\n"
     ]
    }
   ],
   "source": [
    "df = scrap_fifa(16)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
